### ISSUE TITLE
RPROMPT is not displaying in the the terminal Ubuntu 16.04 

### ISSUE THREAD

**Issue by blackode** [chauncey-garrett/zsh-prompt-garrett#11]
Very excited with the prompt but RPROMPT is not displaying . I tried to set RPROMPT in .zshrc file but even that is not displaying . did i miss something  i attached the screen shot below...........

![screenshot from 2016-08-09 19-49-28](https://cloud.githubusercontent.com/assets/9107477/17519663/86a4d198-5e6a-11e6-9bd4-a0b50eefce84.png)

**Comment by blackode** [comment]
It worked when I comment the line in the original  theme file
![screenshot from 2016-08-10 01-36-34](https://cloud.githubusercontent.com/assets/9107477/17531870/6e0418e8-5e9b-11e6-9218-9f06cacd42e6.png)
![screenshot from 2016-08-10 01-37-05](https://cloud.githubusercontent.com/assets/9107477/17531881/7cfe2992-5e9b-11e6-869a-fcc1ac0dfb4e.png)
I commented the above line and it displayed . I do not know what the actual reason is but it worked for me .......
![screenshot from 2016-08-10 01-42-11](https://cloud.githubusercontent.com/assets/9107477/17531924/b462f9b2-5e9b-11e6-9d8f-52440f732ec9.png)
I think he problem is overwriting the problem...........

**Comment by chauncey-garrett** [comment]
Were you by any chance trying out several different prompts?

**Comment by blackode** [comment]
@chauncey-garrett I don't think so.I just followed Instructions like as you said,any way thanks for the nice prompt and its live features.You can close the issue, as you said different prompts might be the reason...........................Thanks for the Reply
I just learned a lot and edited myself from you
![screenshot from 2016-09-18 12-01-22](https://cloud.githubusercontent.com/assets/9107477/18613402/a6b13958-7d97-11e6-8ead-fe1b1978c835.png)

**Comment by chauncey-garrett** [comment]
@blackode Glad you got it working for you :)

Closing the issue. If anyone else experiences a similar problem, please open a new issue and reference this one.
