### ISSUE TITLE
Virtual Environments

### ISSUE THREAD

**Issue by minhoolee** [chauncey-garrett/zsh-prompt-garrett#12]
Hi,

I noticed that if I access a virtual environment through either conda or virtualenvwrapper, the name of the environment is prepended to the left square bracket like so. Is it possible to move that into either the bottom left parentheses or the top right?

![term](https://cloud.githubusercontent.com/assets/10465228/23830792/14ed3658-06d0-11e7-960a-7b8b778e432e.png)

**Comment by chauncey-garrett** [comment]
Setting [VIRTUAL_ENV_DISABLE_PROMPT=1](https://virtualenv.pypa.io/en/stable/reference/#envvar-VIRTUAL_ENV_DISABLE_PROMPT) should be helpful if you just want to disable this information.

Alternatively, you could do the above plus change `ruby-info` to `python-info` in `prompt_garrett_setup` which should work rather nicely if you primarily code in python.
