### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by binarykitchen** [chauncey-garrett/zsh-prompt-garrett#13]
Can you write few sentences on that in the readme? Thx :)

**Comment by kunalkapoor** [comment]
Copy prompt_garrett_setup into `~/.zprezto/modules/prompt/functions/`.
Modify ~/.zpreztorc to add this line `zstyle ':prezto:module:prompt' theme 'garrett'`.
Open a new terminal or reload zsh in the existing terminal to see the prompt.

**Comment by binarykitchen** [comment]
yeah that worked - can you add this to the readme for the others?
