### ISSUE TITLE
Definition of prompt #

### ISSUE THREAD

**Issue by mcowger** [chauncey-garrett/zsh-prompt-garrett#14]
<img width="117" alt="2017-07-29 19_30_56-bash" src="https://user-images.githubusercontent.com/1929548/28750140-224d3964-7495-11e7-96c7-73412b162e9c.png">

Hi Garrett,

Can you help me understand what the `( 3 )` is in the screen shot above.  Its not reference in the docs, and not clear to be from the code.

**Comment by chauncey-garrett** [comment]
https://github.com/chauncey-garrett/zsh-prompt-garrett#shell-level-notification

The shell level `SHLVL` is incremented by one each time a new shell is started. Some common reasons the number can increase are:

- `zsh` was started from within another shell, which could be `zsh`
- a multiplexer like `tmux` is used

Does that help?
