### ISSUE TITLE
Option to turn off the notification?

### ISSUE THREAD

**Issue by aaulia** [chauncey-garrett/zsh-prompt-garrett#15]
Will there be an option to turn off the notification? I assume commenting [this line](https://github.com/chauncey-garrett/zsh-prompt-garrett/blob/67a862a00597c10376d8e6ac9e900c88cca03472/prompt_garrett_setup#L195) out, am I correct?

**Comment by chauncey-garrett** [comment]
I'm not able to test right now but I believe commenting that line out _should_ disable the notification. You may also want to comment the function out as well if you aren't going to use it. 

Alternatively, you can increase the time from 1s to say 30s if you find it triggers too often. See the comments in the function for how to set that.

**Comment by aaulia** [comment]
Yup it works
