### ISSUE TITLE
the "shorten-if-needed" pwd display always shortens all directories past ~

### ISSUE THREAD

**Issue by cbowns** [chauncey-garrett/zsh-prompt-garrett#17]
I use a very wide terminal window (1/2 – full width of a 27" HiDPI screen), but garrett really wants to shorten my pwd:

<img width="1613" alt="screenshot 2017-08-30 12 41 07" src="https://user-images.githubusercontent.com/474/29891599-83ed01c8-8d80-11e7-8777-90b7b82b6ea7.png">

I tried debugging it but the regex used to edit pwd is pretty bonkers, so I just turned off shortening.

**Comment by chauncey-garrett** [comment]
@cbowns Good catch!

I updated the prompt to use the `prompt-pwd` function included within the `prompt` module of prezto. If you're still seeing this issue, you'll want to make note of it upstream -- like you said, the regex is a beast!

You should also now be able to configure it according to https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt#prompt-display-length.

Let me know if there's anything else I can help with!
