### ISSUE TITLE
does the git status: "diverged" actually work?

### ISSUE THREAD

**Issue by cbowns** [chauncey-garrett/zsh-prompt-garrett#21]
I couldn't find a reference to this in the prezto git setup.

you set it here: https://github.com/chauncey-garrett/zsh-prompt-garrett/blob/master/prompt_garrett_setup#L366

but it's not mentioned in prezto's git module, though? https://github.com/sorin-ionescu/prezto/tree/master/modules/git/

**Comment by chauncey-garrett** [comment]
I don't run into the _diverged_ status very often but if I recall correctly, I believe what you'd see would be the up and down arrow separated by a space.

**Comment by cbowns** [comment]
I more meant, I don't think prezto supports it. (Just opened a ticket to add it, though. https://github.com/sorin-ionescu/prezto/issues/1466)

---

I got a test repo in this state:

```
└─❱❱❱ g status                                                            
On branch feature/selfieCapture-ui-changes
Your branch and 'origin/feature/selfieCapture-ui-changes' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
```

but the prompt just shows ahead/behind, per my formatting:

```
~/Dev ahead 1 behind 1 on feature/selfieCapture-ui-changes at 11c4a21
```
