### ISSUE TITLE
Drawing issues on FreeBSD

### ISSUE THREAD

**Issue by tchoutri** [chauncey-garrett/zsh-prompt-garrett#23]
Hi! I just installed your theme, as explained in the README. However, the fallback looks like this:
![capture du 2017-10-17 17-54-06](https://user-images.githubusercontent.com/15848443/31675285-7199cd44-b364-11e7-9684-0bde1091d1a2.png)

And it quite hurts the eye after 20s :/
Do you know what's happening here so I may help?

**Comment by chauncey-garrett** [comment]
I've seen that happen a couple of times before--usually when the terminal gets borked or is not configured properly. At the moment, I can't think of what setting you may need to change.

What happens when you try the `reset` command?

**Comment by chauncey-garrett** [comment]
A couple of other things that could matter are your font choice and that you're using UTF-8 character encoding.

**Comment by tchoutri** [comment]
`reset` has no effect. :/
My `~/.login_conf` specifies UTF-8 for the charset and LANG:

```
me:\
        :charset=UTF-8:\
        :lang=fr_FR.UTF-8:\
        :setenv=LC_COLLATE=C:
```

I'll try to investigate that when I have more time on my hands, but thanks for your attention. =)

**Comment by chauncey-garrett** [comment]
This may help you: http://invisible-island.net/ncurses/ncurses.faq.html#no_line_drawing

Are you using `screen` or `tmux` by chance?

Also, checking the output of `locale` may be useful as well.

**Comment by tchoutri** [comment]
Oh, fun fact, using tmux manages to render the line well!
However, even if my non-tmux session's variables match the tmux ones, it does nothing: 

Without tmux
![capture du 2017-10-31 08-21-32](https://user-images.githubusercontent.com/15848443/32211844-af35bcc0-be14-11e7-8912-7cf86f1f17c5.png)

With tmux
![capture du 2017-10-31 08-21-53](https://user-images.githubusercontent.com/15848443/32211834-a7544814-be14-11e7-9511-08e0630e06ec.png)

**Comment by tchoutri** [comment]
Oh, fun fact, using tmux manages to render the line well!
However, even if my non-tmux session's variables match the tmux ones, it does nothing: 

Without tmux
![capture du 2017-10-31 08-21-32](https://user-images.githubusercontent.com/15848443/32211844-af35bcc0-be14-11e7-8912-7cf86f1f17c5.png)

With tmux
![capture du 2017-10-31 08-21-53](https://user-images.githubusercontent.com/15848443/32211834-a7544814-be14-11e7-9511-08e0630e06ec.png)

**Comment by tchoutri** [comment]
So, I automatically spawn tmux (new or attach) when I ssh to my freebsd box.
I guess that's my workaround.

**Comment by chauncey-garrett** [comment]
I normally do that anyhow 😉 but I know that doesn’t solve the issue here. It’s been a bit of a pain point for me because there’s really not that much out there about terminal line drawing and escape codes and the like (or at least I don’t know where to dig). 

I’ll improve it if I ever come across something that will do so but until then I guess we’re stuck with workarounds. 

Thanks for trying!
