### ISSUE TITLE
Continuation Prompt is incomplete

### ISSUE THREAD

**Issue by mgeorgy** [chauncey-garrett/zsh-prompt-garrett#25]
I've just installed prompt and noticed that the continuation prompt is incomplete.  Using the example, I'm not seeing (for) in the prompt:

┌─( ~ )────────────────────────────────────────────────────────────────────────────────────( @MacBook-Pro )─┐
└─❱❱❱ for i in {1..10}                                                                            1 ⏎  +106 17:31 ❰─┘
() ❱❱❱

Is this a configurable option, or is there a problem with my install?

**Comment by chauncey-garrett** [comment]
Looks like this is related to #16.
