### ISSUE TITLE
prompt_garrett_setup:28: command not found: pmodload

### ISSUE THREAD

**Issue by Changzw** [chauncey-garrett/zsh-prompt-garrett#6]
I use MacBook. when executing prompt_garrett_setup, i get one tip  "prompt_garrett_setup:28: command not found: pmodload"

**Comment by chauncey-garrett** [comment]
The shell prompt requires that you use [Prezto](https://github.com/sorin-ionescu/prezto).

`pmodload` is a function to load prezto modules and can be found in the [`init.zsh`](https://github.com/sorin-ionescu/prezto/blob/master/init.zsh) file.

**Comment by polliard-jmfe** [comment]
This issue is still an issue.  Prezto is installed, pmodload 'helper' works just fine outside of the script.

```
~/D/zsh-prompt-garrett ❯❯❯ pmodload 'helper'
~/D/zsh-prompt-garrett ❯❯❯ echo $?
0
```

However,
```
~/D/zsh-prompt-garrett ❯❯❯ ./prompt_garrett_setup
./prompt_garrett_setup:27: command not found: pmodload
```

```
~/D/zsh-prompt-garrett ❯❯❯ which zsh
/bin/zsh
~/D/zsh-prompt-garrett ❯❯❯ which env
/usr/bin/env
```

Any thoughts?

**Comment by polliard-jmfe** [comment]
Ok, so the issue is... Just copy it to the right location... Lol.. First custom theme I have ever installed... Had to read the zprezto docs to find out that I needed to copy the prompt_garrett_setup to ~/.zprezto/modules/prompt/functions . .. Might want to add that to the README.md for us newbs :)
