### ISSUE TITLE
Not getting any of git status, git remote status, git prompt info and git SHA information

### ISSUE THREAD

**Issue by yeongsheng-tan** [chauncey-garrett/zsh-prompt-garrett#7]
After cloning https://github.com/chauncey-garrett/zsh-prezto and following the instructions, I'm not getting the expected behaviour of git info on my dirs which are git managed projects.

What would you need to help me out?

**Comment by chauncey-garrett** [comment]
Are you using Prezto? If so, do you have the git module enabled?

**Comment by yeongsheng-tan** [comment]
Yes. I'm using your fork of prezto.

And yes, after I've enabled 'git' module in ~/.zpreztorc, it works like a charm.

**Comment by chauncey-garrett** [comment]
Glad to hear!
